# Generated by Django 4.2.27 on 2025-12-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_isbn_alter_book_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-fiction')], default='fiction', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='sub_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
