# Generated by Django 4.2.27 on 2025-12-15 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_book_genre_book_sub_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserBookRating',
        ),
        migrations.AddIndex(
            model_name='userfavoritebook',
            index=models.Index(fields=['user'], name='books_userf_user_id_948d74_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavoritebook',
            index=models.Index(fields=['book'], name='books_userf_book_id_ed94dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritebook',
            unique_together={('user', 'book')},
        ),
    ]
