# Generated by Django 4.2.27 on 2025-12-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_userfavoritebook_delete_userbookrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritebook',
            name='explanation',
            field=models.TextField(blank=True, help_text='Why you love this book', max_length=500),
        ),
    ]
