# Generated by Django 4.2.27 on 2025-12-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_userfavoritebook_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_popular', 'title'], name='books_book_is_popu_5cb10d_idx'),
        ),
    ]
