# Generated by Django 4.2.27 on 2026-01-15 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_alter_book_created_at_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToBeReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text="Optional notes or why it's on your TBR", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_by', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbr_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user'], name='books_tober_user_id_467c78_idx'), models.Index(fields=['book'], name='books_tober_book_id_c0e095_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
