# Generated by Django 4.2.27 on 2026-01-20 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0009_tobereadbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_recommendation_emails', models.BooleanField(default=True, help_text='Whether to receive new book recommendation emails')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When the user unsubscribed from recommendation emails', null=True)),
                ('last_recommendation_email_sent', models.DateTimeField(blank=True, help_text='When the last recommendation email was sent to this user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Email Preferences',
                'verbose_name_plural': 'User Email Preferences',
            },
        ),
    ]
