# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_useremailpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub_genre',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Mystery & Thriller', 'Mystery & Thriller'),
                    ('Sci-Fi', 'Sci-Fi'),
                    ('Fantasy', 'Fantasy'),
                    ('Historical Fiction', 'Historical Fiction'),
                    ('Horror', 'Horror'),
                    ('General Fiction', 'General Fiction'),
                    ('Biography', 'Biography'),
                    ('History', 'History'),
                    ('Science', 'Science'),
                    ('Philosophy & Religion', 'Philosophy & Religion'),
                    ('Psychology & Self-Help', 'Psychology & Self-Help'),
                    ('Business & Finance', 'Business & Finance'),
                    ('Politics', 'Politics'),
                    ('Humor', 'Humor'),
                    ('True Crime', 'True Crime'),
                    ('Reference', 'Reference'),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
