# Generated by Django 4.2.27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0012_add_classic_sub_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-marked_at',),
                'unique_together': {('user', 'book')},
                'indexes': [
                    models.Index(fields=['user'], name='books_userre_user_id_idx'),
                    models.Index(fields=['book'], name='books_userre_book_id_idx'),
                ],
            },
        ),
    ]
